added extra encryption algorithm
openpreserve/jhove pull request #621
Opened 2020-06-05 15:25 UTC by samalloing

Hi @carlwilson 

In this pull request I added code for a new encryption algorithm 256-bit AES. It is allowed in the extensionlevel 3 as a new encryption algorithm. This code is independent of the Extension level code I mailed you about.

Sam

2020-06-05 16:02 UTC, david-russo reviewed
More good work. Thanks, Sam.

2020-06-05 16:02 UTC, david-russo commented on jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
> +				if (algValue == 5) {
These three lines could be removed to make the following code a part of the preceding and identical `if` condition, only requiring the check to happen once.

2020-06-05 16:02 UTC, david-russo commented on jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
> +						throw new PdfInvalidException // PDF-HUL-15X
These message ID markers (`// PDF-HUL-15X`) are a hold over from a refactoring that took place some time ago and are no longer necessary now that message IDs are encoded in `MessageConstants` names (like below). Feel free to remove them from any code you happen to work on, or leave them — no real issue here.

2020-06-05 16:02 UTC, david-russo commented on jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages.properties
> +PDF_HUL_153 = The mandatory UE is missing
To add a little more detail and bring them in line with other similar PDF messages:
"Encrypt dictionary has no OE key or it has a null value"
"Encrypt dictionary has no UE key or it has a null value"

2020-06-05 16:53 UTC, samalloing commented
Thanks again @david-russo . I updated the pull request

2020-06-05 17:28 UTC, david-russo approved these changes

2020-06-10 23:17 UTC, carlwilson commented
Thanks both @samalloing and @david-russo

2020-06-10 23:39 UTC, carlwilson commented
Interesting, this has [broken the build](https://travis-ci.org/github/openpreserve/jhove/builds/697042154). The issue is that the IDs for the message resources are mal-formed and the messages can't be loaded. I've added a review comment that requests changes.

2020-06-10 23:40 UTC, carlwilson requested changes
See comment inline but good work overall thanks @samalloing

2020-06-10 23:40 UTC, carlwilson commented on jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages.properties
> +PDF_HUL_151 = Unexpected error occurred while attempting to read the cross-reference table
These are the culprits, they should be using hyphens, not underscores.

2020-06-11 06:08 UTC, samalloing commented
I updated it, sorry about the mistake @carlwilson

2020-06-11 21:11 UTC, carlwilson commented
> I updated it, sorry about the mistake @carlwilson

No need at all, that's what the autotests are for, thanks @samalloing

2020-06-13 17:05 UTC, carlwilson approved these changes

2020-06-14 09:48 UTC, merged