Addressing issue #93: CrossRefStream incorrectly assumes /Index value is a 2 element array
openpreserve/jhove pull request #97
Opened 2016-07-19 14:05 UTC by paulmer

array containing an arbitrary set of starting object number and object
count pairs instead of a single pair.

Calculate number of objects using final start/count pair.  (Actual number
will be less than or equal to this value.)

Modified reading loop to read only objects in the index ranges.

Modified PdfModule to test object number against stream's index instead of
a range from 0 to the last object number.

Attempt to conform to PDF specification
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference15_v6.pdf, page 83 and PDF versions 1.6 and 1.7.

2016-09-12 13:11 UTC, smmorrissey commented
Sheila +1

2016-09-19 12:51 UTC, pmay commented
+1

2016-09-19 13:54 UTC, asciim0 commented
+1

2016-10-26 16:38 UTC, david-russo requested changes
Thanks for the patch Paul, and good catch on the discrepancy with the spec. The code is largely fine and only requires some minor clean-up.

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
> +	private int _index_size;
`_index_size` appears to be unnecessary since the same value can be retrieved from `_index.length`.

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
> +	private class index_range {
Similarly, all class names should be camel-case with an initial capital letter, i.e. `IndexRange`.

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
> +        return _index[_index_size - 1].start + _index[_index_size - 1].len;
Like the original method, this seems like a convoluted way to calculate the value already stored in `_size`. Is there a reason we can't simply return that?

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
>      private int _entriesRead;
With the addition of `_read_index` below, `_entriesRead` is no longer in use and can be safely removed.

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
> +	private int _read_index;
Try and match any surrounding whitespace conventions. In this case 4 spaces instead of a tab. JHOVE's source code is currently a mess with indentation, but we should avoid adding to the confusion.

Also, the JHOVE (and [Java](http://www.oracle.com/technetwork/java/codeconvtoc-136057.html)) style convention for common variable names is to have them camel-cased with lowercase initial letters, e.g. `_readRange`, such as in the surrounding code.

2016-10-26 16:38 UTC, david-russo commented on jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/CrossRefStream.java
> +	public boolean isValidObject(int objNum) {
Please add JavaDocs for any new methods.

2017-03-20 19:49 UTC, carlwilson commented
Closed by #188

2017-03-20 19:49 UTC, closed without merging